name: Bug Report
description: Report a bug with tosu
title: "bug: "
labels: ["unlabeled"]
body:
  - type: markdown
    attributes:
      value: |

        ### tosu bug report form
        Thank you for helping tosu get better! Before completing the form, please follow the next steps:
        1. In the settings page, enable `Debugging Mode`.
        2. Restart osu! and tosu.
        3. Reproduce the issue.
        4. Close tosu.
        

  - type: textarea
    id: issue-description
    attributes:
      label: Describe the issue
      description: |
        What happened? Please include steps to reproduce if possible.
        If you're having issues with the tosu overlay, please also mention your hardware.
      placeholder: |
        tosu crashed unexpectedly!

        1. launch tosu
        2. wait a little
        3. crash happens
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: Which OS are you using?
      placeholder: "Windows 10 / Windows 11 / Ubuntu 22.04 / Arch 2025.06.01"
    validations:
      required: true

  - type: input
    id: osu-version
    attributes:
      label: osu! version
      description: Which stream and version of osu! are you using?
      placeholder: "Stable v20250619 / Cutting Edge v20250617 / Lazer v2025.607.0 / Tachyon v2025.616.0"
    validations:
      required: true

  - type: textarea
    id: media
    attributes:
      label: Media
      description: Drag and drop here or paste links to screenshots or videos that show the issue.
      placeholder: "Drag and drop files here."

  - type: textarea
    id: logs
    attributes:
      label: Log Files
      description: Drag and drop the debug logs here (The latest file in `./logs/`).
      placeholder: "Drag and drop files here."

  - type: checkboxes
    id: confirmation
    attributes:
      label: Checklist
      options:
        - label: I made sure the issue was not reported before.
          required: true
        - label: I am using the latest tosu version at the time of the report.
          required: true
