name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["feature request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for tosu!
        Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: Tell us about your idea
    validations:
      required: true

  - type: textarea
    id: why-needed
    attributes:
      label: Why is this feature needed?
      description: Explain the use case and benefits of this feature
      placeholder: Describe why you need this functionality and how it would help you or others
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
      placeholder: Have you found any workarounds or alternative approaches?
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here
      placeholder: Any additional information, mockups, or examples that might help
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and pull requests to make sure this is not a duplicate
          required: true
        - label: This feature would be useful to other users, not just me
          required: false
